steps:
# 1) Build your Node.js “Hello World” app into a container
- name: "gcr.io/buildpacks/builder:v1"
  args:
  - "-path=."
  - "-tag=gcr.io/$PROJECT_ID/hello-service"

# 2) Deploy the resulting image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
   gcloud run deploy hello-service \
    --image=gcr.io/$PROJECT_ID/hello-service \
    --region=us-central1 \
    --platform=managed \
    --quiet

# Tell Cloud Build to push this image when it's built
images:
 - "gcr.io/$PROJECT_ID/hello-service"

# Give yourself up to 10 minutes, just in case
timeout: "600s"